#!/bin/bash

# list the content of the home directory

ls -lh /$HOME/

# reads the user input and saves it under $infile variable

echo "Please select the input file [ENTER]: "
read infile

# run the 2-pas encoding for infile and rename the output file from xxx.mxf -> xxx.mp4

ffmpeg -y -i $infile \
-c libx264 -preset medium -b:v 19M -maxrate 20M -bufsize 40M -pass 1 \
-c:a aac -ac 2 -b:a 192k \
-f mp4 /dev/null \
&& ffmpeg -i $infile \
-c:v libx264 -preset medium -b:v 19M -maxrate 20M -bufsize 40M -pass 2 \
-c:a aac -ac 2 -b:a 192k \
${infile%.mxf}.mp4

# shows the stats of the transcoded file 

echo
echo "The transcoding finished successfully, these are the stats of your transcoded file:"
echo

ffprobe ${infile%.mxf}.mp4 &> test.log \
&& grep -i video test.log \
&& grep -i audio test.log \
&& rm test.log
